### PR TITLE
Fix hung pv discovery ensure it times out

### LINKED ISSUE #348: PV discovery hangs, and makes the page freeze
During last testing encountered this behaviour. Happens when the creation of `mig-plan` is started from the UI. Independent on the selected namespace and presence of the PVs in the namespace, the discovery runs for some time and then blocks the window indefinitely.

### PR DESCRIPTION
**Pull request by eriknelson**
Closes #348 

If pv discovery ever "timed out" (ran past the desired amount of ticks), it would fall into an infinite while loop that would deadlock the UI thread. This at least will prevent a deadlock and alert the user to a timeout.

### CODE REVIEW

File: src/app/plan/duck/sagas.ts [hunk 1]
```diff
@@ -26,6 +29,14 @@ function* checkPVs(action) {
           break;
       }
       yield delay(params.delay);
+    } else {
+      // PV discovery timed out, alert and stop polling
+      pvsFound = true; // No PVs timed out
+      Creators.stopPVPolling();
+      yield put(alertError("Timed out during PV discovery"));
```
Comment (ibolton336) [inline src/app/plan/duck/sagas.ts]: Looks good & nice catch 👍
