### PR TITLE
Fixed status propagaton on failed migrations

### LINKED ISSUE #315: mig-ui says migration succeeded when it failed
migmigration

```
Name:         72188780-a195-11e9-95aa-f318654dbe30
Namespace:    mig
Labels:       <none>
Annotations:  touch=1657d18f-736a-4c6c-834c-bf37d0d3119f
API Version:  migration.openshift.io/v1alpha1
Kind:         MigMigration
Metadata:
  Creation Timestamp:  2019-07-08T15:31:24Z
  Generation:          4
  Resource Version:    3930797
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/mig/migmigrations/72188780-a195-11e9-95aa-f318654dbe30
  UID:                 722bc9cd-a195-11e9-a219-0ed41539d98e
Spec:
  Mig Plan Ref:
    Name:        test
    Namespace:   mig
  Quiesce Pods:  true
  Stage:         false
Status:
  Conditions:
    Category:              Advisory
    Last Transition Time:  2019-07-08T15:31:37Z
    Message:               The migration has completed successfully.
    Reason:                BackupFailed
    Status:                True
    Type:                  Succeeded
    Category:              Critical
    Last Transition Time:  2019-07-08T15:31:37Z
    Message:               The migration has failed.  See: Errors.
    Reason:                BackupFailed
    Status:                True
    Type:                  Failed
  Errors:
    Backup: mig/72188780-a195-11e9-95aa-f318654dbe30-68fk6 failed.
  Phase:            BackupFailed
  Start Timestamp:  2019-07-08T15:31:24Z
Events:             <none>
```

ui displays:
```
test 1 origin3-dev host jmontleo-velero 0 Migration Succeeded  
```

The icon on the left is red instead of green like the one that succeeded so it seems the actual state is detected and maybe just the text needs fixed for this case.

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Here is a case, where the fix makes a change:
Before - last status gets propagated to the failed builds, which has no migrations executed:
image
Appearance after the fix:
image (1)

### CODE REVIEW

File: src/client/resources/conversions.ts [hunk 1]
```diff
@@ -282,7 +282,7 @@ export function createMigMigration(
       // TODO: We need to wire these up to the UI when stage is implemented
       // and we've more thouroughly tested quiesce/stage combos in conjunction
       // with the controller and velero.
-      quiescePods: true,
+      quiescePods: !isStage,
```
Comment (eriknelson) [inline src/client/resources/conversions.ts]: This is tricky, and it's not strictly a function of whether or not we're doing a stage. During a migration, the user is presented an option to quiesce or not. I would remove this from the PR and hit later in a distinct PR, since it's more nuanced. See: https://github.com/fusor/mig-ui/issues/224

File: src/app/plan/duck/operations.ts [hunk 2]
```diff
@@ -241,7 +241,6 @@ const addPlan = migPlan => {
           if (pvsDiscovered) {
             dispatch(Creators.updatePlan(plan));
             dispatch(pvFetchSuccess());
-            dispatch(commonOperations.alertSuccessTimeout('Found PVs!'));
```
Comment (eriknelson) [inline src/app/plan/duck/operations.ts]: This has been addressed in #340, it's fine to leave but just letting you know.

**Comment by eriknelson** [comment]
You'll have to rebase on the recent PR we added.

File: src/client/resources/conversions.ts (hunk 1 above)
Comment (Danil-Grigorev) [reply src/client/resources/conversions.ts]: Ok, I'll try to implement check box there later. Thanks for the suggestion, the issue https://github.com/fusor/mig-ui/issues/323 implied that it should be connected directly to the `stage` logic for now.

**Comment by eriknelson** [comment]
This is definitely fixing a bug in the status logic, but I don't think it's actually fixing #315. That issue describes the status reporting success when a migration has **failed**, but in your screenshots, you haven't actually run any migrations on your other plans. As far as I'm aware, we don't actually have an issue for what you're demonstrating, so you might have found and fixed a new bug.
